package travelers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BondHighLevelDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String businessType;
   private java.lang.String bondDetails;
   private java.lang.String bondDetailsPremiumsForms;
   private java.lang.String billandIssue;
   private java.lang.String validateandFormsSelection;

   public BondHighLevelDO()
   {
   }

   public java.lang.String getBusinessType()
   {
      return this.businessType;
   }

   public void setBusinessType(java.lang.String businessType)
   {
      this.businessType = businessType;
   }

   public java.lang.String getBondDetails()
   {
      return this.bondDetails;
   }

   public void setBondDetails(java.lang.String bondDetails)
   {
      this.bondDetails = bondDetails;
   }

   public java.lang.String getBondDetailsPremiumsForms()
   {
      return this.bondDetailsPremiumsForms;
   }

   public void setBondDetailsPremiumsForms(
         java.lang.String bondDetailsPremiumsForms)
   {
      this.bondDetailsPremiumsForms = bondDetailsPremiumsForms;
   }

   public java.lang.String getBillandIssue()
   {
      return this.billandIssue;
   }

   public void setBillandIssue(java.lang.String billandIssue)
   {
      this.billandIssue = billandIssue;
   }

   public java.lang.String getValidateandFormsSelection()
   {
      return this.validateandFormsSelection;
   }

   public void setValidateandFormsSelection(
         java.lang.String validateandFormsSelection)
   {
      this.validateandFormsSelection = validateandFormsSelection;
   }

   public BondHighLevelDO(java.lang.String businessType,
         java.lang.String bondDetails,
         java.lang.String bondDetailsPremiumsForms,
         java.lang.String billandIssue,
         java.lang.String validateandFormsSelection)
   {
      this.businessType = businessType;
      this.bondDetails = bondDetails;
      this.bondDetailsPremiumsForms = bondDetailsPremiumsForms;
      this.billandIssue = billandIssue;
      this.validateandFormsSelection = validateandFormsSelection;
   }

}