package travelers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Bond implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int policynumber;
   private java.lang.String status;

   public Bond()
   {
   }

   public int getPolicynumber()
   {
      return this.policynumber;
   }

   public void setPolicynumber(int policynumber)
   {
      this.policynumber = policynumber;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public Bond(int policynumber, java.lang.String status)
   {
      this.policynumber = policynumber;
      this.status = status;
   }

}