package travelers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewBondEligible implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int policynumber;
   private java.lang.Boolean eligible;
   private java.lang.String reason;

   private java.lang.String reason2;

   public NewBondEligible()
   {
   }

   public int getPolicynumber()
   {
      return this.policynumber;
   }

   public void setPolicynumber(int policynumber)
   {
      this.policynumber = policynumber;
   }

   public java.lang.Boolean getEligible()
   {
      return this.eligible;
   }

   public void setEligible(java.lang.Boolean eligible)
   {
      this.eligible = eligible;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.lang.String getReason2()
   {
      return this.reason2;
   }

   public void setReason2(java.lang.String reason2)
   {
      this.reason2 = reason2;
   }

   public NewBondEligible(int policynumber, java.lang.Boolean eligible,
         java.lang.String reason, java.lang.String reason2)
   {
      this.policynumber = policynumber;
      this.eligible = eligible;
      this.reason = reason;
      this.reason2 = reason2;
   }

}