package travelers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Principal implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Principal() {
    }

}