package travelers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private travelers.BondHighLevelDO bondHighLevelDO;
   private java.lang.Boolean highPriority;

   public RequestDO()
   {
   }

   public travelers.BondHighLevelDO getBondHighLevelDO()
   {
      return this.bondHighLevelDO;
   }

   public void setBondHighLevelDO(travelers.BondHighLevelDO bondHighLevelDO)
   {
      this.bondHighLevelDO = bondHighLevelDO;
   }

   public java.lang.Boolean getHighPriority()
   {
      return this.highPriority;
   }

   public void setHighPriority(java.lang.Boolean highPriority)
   {
      this.highPriority = highPriority;
   }

   public RequestDO(travelers.BondHighLevelDO bondHighLevelDO,
         java.lang.Boolean highPriority)
   {
      this.bondHighLevelDO = bondHighLevelDO;
      this.highPriority = highPriority;
   }

}