package travelers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestDO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean highPriority;

   private java.lang.String comments;

   public RequestDO()
   {
   }

   public java.lang.Boolean getHighPriority()
   {
      return this.highPriority;
   }

   public void setHighPriority(java.lang.Boolean highPriority)
   {
      this.highPriority = highPriority;
   }

   public java.lang.String getComments()
   {
      return this.comments;
   }

   public void setComments(java.lang.String comments)
   {
      this.comments = comments;
   }

   public RequestDO(java.lang.Boolean highPriority, java.lang.String comments)
   {
      this.highPriority = highPriority;
      this.comments = comments;
   }

}