package travelers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Underwriter implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Underwriter() {
    }

}