package travelers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WhichAgendaGroupDO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public WhichAgendaGroupDO() {
    }

}