
package travelers;
rule "BondDetailValidations"
	dialect "mvel"
no-loop true
//lock-on-active true
	agenda-group "bonddetailvalidations"
when
   $b:travelers.Bond( )
   $neb:NewBondEligible( reason=="Passed Premium Validation")

then
System.out.println("Before Passed BondDetailvalidations");

modify ($neb){
setReason2("BondDetailValidationPassed");
}
System.out.println("After Passed BondDetailvalidations");
end

