
package travelers;
rule "BondDetailValidations"
	dialect "mvel"
no-loop true
lock-on-active true
	agenda-group "bonddetailvalidations"
when
   $b:travelers.Bond( )
   $neb:NewBondEligible( reason=="Passed Premium Validation")

then
System.out.println("Passed BondDetailvalidations");

//NewBondEligible neb2=new NewBondEligible( )
//neb2.setEligible(true);
  // neb2.setReason("BondDetailValidationPassed"); 
 //insert (neb2);
 
 modify ($neb){
     setEligible(true);
     setReason2("BondDetailValidationPassed");
 }

end

