
package travelers;
rule "BondDetailValidations"
	dialect "mvel"
no-loop true
lock-on-active true
	agenda-group "bonddetailvalidations"
when
travelers.Bond( )
$neb:travelers.NewBondEligible( reason=="Passed Premium Validation")

then
System.out.println("Passed BondDetailvalidations");
modify $neb{
setEligible(true);
   setReason("BondDetailValidationPassed"); 
}
//travelers.NewBondEligible neb = new travelers.NewBondEligible( );

end

