

package travelers;
query "get whichdo"()
    whichagendagroupdo : WhichAgendaGroupDO()
end
rule "OtherValidations2"
	dialect "mvel"
no-loop true
	agenda-group "othervalidations2"
when

travelers.WhichAgendaGroupDO(agendaGroupName=="othervalidations")

then
Bond $var0 = new Bond();
		
		insert( $var0 );
		
System.out.println("hi from othervalidations2");
kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup("othervalidations").setFocus();
end
