

package travelers;
query "get whichdo"()
    whichagendagroupdo : WhichAgendaGroupDO()
end
rule "OtherValidations2"
	dialect "mvel"
no-loop true
//	agenda-group "othervalidations2"
when

travelers.WhichAgendaGroupDO(agendaGroupName=="othervalidations")

then
Bond $var0 = new Bond();
		
		insert( $var0 );
	Transaction t=	new Transaction( );
	t.setCommissionrate(22);
	t.setSpecialcommission(600);
	insert (t);
    NewBondEligible $neb=new NewBondEligible( );
    insert ($neb);
    
		
System.out.println("hi from othervalidations2");
kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup("premiumvalidation").setFocus();
end
